### ISSUE TITLE
Bug: Right-clicking a picture doesn't invoke the right-click context menu

### ISSUE THREAD

**Issue by Skyyblaze** [riyasy/FlyPhotos#10]
As requested I'm opening a bug report as Fly doesn't open a context-menu when right-clicking a picture for me. No matter what I do or on which file I try it on nothing happens. Right-clicking next to the picture makes Fly go windowed as intended.

I'm using Fly 2.2.0 and Windows 11 23H2 22631.3593 and this feature never worked for me.

**Comment by riyasy** [comment]
Did you use mouse right click or any other means?

**Comment by Skyyblaze** [comment]
@riyasy I'm using the default Right-Click function of my mouse, no macros or anything else involved.

**Comment by Skyyblaze** [comment]
I saw the new version but sadly a full, clean reinstall of 2.2.1 didn't help at all with the issue. I can still right-click next to the image to make fly exit fullscreen however right clicking on a picture still doesn't trigger a menu or any kind of reaction. It's as if fly simply isn't registering the right-click on the picture. The log-file shows nothing but this, I opened a single picture in a folder as a test:

`2024-08-01T13:51:42.183|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|1 files listed from Explorer`

**Comment by riyasy** [comment]
I added error checking in that part solely based on this bug. I have tested this Fly on new installations of Win11 and Win10. And in Win11, both with old and new style context menu enabled. (What ever style is selected in Windows 11, Fly will display the win 10 style full context menu as seen in other third party integrations).
Are you able to see the explorer context menu from other third party applications say like Everything app or some other app which you use?(https://www.voidtools.com/). In everything app, if we right click any file item after search, the default explorer context menu is shown. I have employed the same approach.

**Comment by Skyyblaze** [comment]
@riyasy Thanks for continuing to look into it! I think you might be onto something here. I do use the classic right-click menu in Windows 11 with an Acrylic background via StartAllBack, could that be the culprit? I never had issues with any other program though and the right-click menu works no problem in Everything:

![grafik](https://github.com/user-attachments/assets/a1906b70-1e53-4486-aaa1-5d82c40b44e4)

**Comment by riyasy** [comment]
Ok. I don't understand the exact reason why you are not getting it. I have tested in several machines and could not get the issue. Anyway I have fully rewrote the ContextMenu part in CPP native code instead of C#. 
Please check the 2.2.2 installer from following link. As unsafe CPP code is increasing, Windows security may flat it randomly. 

https://drive.google.com/file/d/1EzlAsO35UfwKd0LxvrUy_W3yQgGq3iGW/view?usp=sharing

**Comment by riyasy** [comment]
@Skyyblaze , Were you able to have a look?

**Comment by Skyyblaze** [comment]
@riyasy Sorry I completely missed your earlier message! I tried the 2.2.2 build now and sadly nothing changed. I am sorry if I drive you crazy with this, I don't understand myself what's going on but I appreciate your work.

**Comment by riyasy** [comment]
@Skyyblaze , Did you get something like "Showing context menu failed" in the log file? 

I installed StartAllBack and checked, but still context menu showed up. The only thing remaining is a german windows installation. :-)

**Comment by Skyyblaze** [comment]
@riyasy No, the only thing my log file gets populated with seems normal:

`2024-08-01T13:51:42.183|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|1 files listed from Explorer
2024-08-01T23:56:32.451|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|24 files listed from Explorer
2024-08-01T23:57:28.132|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|24 files listed from Explorer
2024-08-03T06:21:36.234|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|80 files listed from Explorer
2024-08-04T14:41:48.670|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|111 files listed from Explorer
2024-08-04T19:05:20.716|Trace|FlyPhotos.Utils.Util.FindAllFilesFromExplorerWindowNative|111 files listed from Explorer`

It is indeed weird, I would be stumped if the language was the culprit but I've seen weirder things so there's that haha. One thing I did notice, my right-click and my left-click behave exactly the same in fly, is that intended that you can move the picture while holding right-click?

**Comment by Skyyblaze** [comment]
Well I'm not sure what to say. Upon updating Fly to 2.3.0 it wouldn't work at all anymore so I did a clean re-install (as I did before) and now the right-click menu works haha.

**Comment by riyasy** [comment]
That's good to hear.
