### ISSUE TITLE
Suggestion: Add printing as in Picasa

### ISSUE THREAD

**Issue by slet-mig** [riyasy/FlyPhotos#13]

**Comment by riyasy** [comment]
Are you not able to right click on the displayed photo and select print using the explorer shell menu?
Or are you implying Picasa like special print handling instead of the system default?

**Comment by slet-mig** [comment]
I mean be able to several print images on one page - select how many photos on one paper, etc.

**Comment by riyasy** [comment]
I won't be able to take this up at the moment as I am a solo developer.
