### ISSUE TITLE
Suggestion: Add option to remove Fly Photos from Right-Click context menu

### ISSUE THREAD

**Issue by Skyyblaze** [riyasy/FlyPhotos#2]
When setting Fly as the default option for picture files having it also in the right-click context menu seems redundant so an option to remove that would be nice.

**Comment by riyasy** [comment]
In RegEdit, remove HKEY_CLASSES_ROOT\*\shell\Open with Fly\

**Comment by Skyyblaze** [comment]
Okay that's easy, thanks! :) Still might be great to have it in the GUI eventually.

**Comment by riyasy** [comment]
The **"Open with Fly"** has been made optional in the installer.
Available in 2.5.16
