### ISSUE TITLE
Suggestions: Add the ability to scroll through images using mouse wheel

### ISSUE THREAD

**Issue by vpsj** [riyasy/FlyPhotos#8]
Just bought a new Laptop, and tried this out since Picasa is behaving weird on Windows 11. 

Fly is pretty close to Picasa, but it's missing out on some minor (and yet key) features:

1) You can zoom with the mouse wheel on the image in Picasa. This is the same here, however, in Picasa if you hover your mouse down when the image preview strip becomes visible, you can scroll through the images using the same mouse wheel. This is being sorely missed on Fly

2) You can double click on the outside area to change the image display from full screen to window mode. However, if you double click the darkened border area again, you cannot go back to full screen mode like you can in Picasa. 

I sincerely request you to add these features in and it will be the perfect Picasa replacement

**Comment by riyasy** [comment]
The ribbon feature was deliberately not added as photo navigation was made so fast such that the user won't need to check the thumbnails.

1. Since mouse scroll is already tied to the zoom feature, I shall try to add a modifier key which we can press and then scroll the mouse to navigate through the photo list like we press the arrow keys.
2. Shall check.

Shall try to incorporate both these in the next version.

**Comment by riyasy** [comment]
@vpsj, I am implementing this feature. **In the next version**, if you scroll after pressing CTRL key, we will navigate through photos. Also if we keep the mouse over the next,back button on screen and scroll, you will be able to navigate through photos. If you keep the mouse over rotate button and scroll, then you will be able to navigate through photos.

**Comment by riyasy** [comment]
@vpsj, I am implementing this feature. **In the next version**, if you scroll after pressing CTRL key, we will navigate through photos. Also if we keep the mouse over the next,back button on screen and scroll, you will be able to navigate through photos. If you keep the mouse over rotate button and scroll, then you will be able to navigate through photos.

**Comment by vpsj** [comment]
That's brilliant!

Thank you for being so proactive:)

**Comment by riyasy** [comment]
Lot of scroll wheel options are added. Check latest 2.3.0 release notes.

**Comment by riyasy** [comment]
Lot of scroll wheel options are added. Check latest 2.3.0 release notes.
